server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

auth_enabled: false

common:
  path_prefix: /var/loki
  storage:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /var/loki/chunks

compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 5m
  retention_enabled: true
  delete_request_cancel_period: 24h

limits_config:
  retention_period: 720h # 30d
  ingestion_burst_size_mb: 16
  ingestion_rate_mb: 8
  max_cache_freshness_per_query: 10m

query_range:
  parallelise_shardable_queries: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h

