server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            kind: kind
            status: status
            instance_id: instance_id
            instance_role: instance_role
            node: node
            name: name
      - regex:
          expression: '(?i)(?:level=|\b)(?:(?P<level_info>info|inf)|(?P<level_warn>warn|warning|wrn)|(?P<level_err>error|err)|(?P<level_crit>crit|critical|crt)|(?P<level_dbg>dbg|debug)|(?P<level_trc>trace))\b'
      - regex:
          expression: '(?P<is_health_check>GET .*?/(?:health|state)\s+HTTP)'
      - template:
          source: level
          template: |
            {{- if .level_info -}}info
            {{- else if .level_warn -}}warning
            {{- else if .level_err -}}error
            {{- else if .level_crit -}}critical
            {{- else if .level_dbg -}}debug
            {{- else if .level_trc -}}trace
            {{- else -}}unknown
            {{- end -}}
      - template:
          source: health_check
          template: '{{ if .is_health_check }}true{{ else }}false{{ end }}'
      - labels:
          kind:
          status:
          instance_id:
          instance_role:
          node:
          name:
          level:
          health_check:
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '.+'
        action: keep
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: /var/lib/docker/containers/$1/$1-json.log
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'log_stream'
      - replacement: 'docker'
        target_label: 'job'
      - replacement: '${INSTANCE_ID}'
        target_label: 'instance_id'
      - replacement: '${INSTANCE_IP}'
        target_label: 'instance_ip'
