version: "3.9"

services:
  promtail:
    image: grafana/promtail:2.9.7
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file: .env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/promtail:/var/lib/promtail
      - ./data/logs:/var/log/metrics
    restart: unless-stopped

  metrics-collector:
    build:
      context: ../metrics-collector
    env_file: .env
    environment:
      - INSTANCE_ROLE=remote
      - METRICS_INTERVAL=${METRICS_INTERVAL:-15}
      - METRICS_PROCESS_LIMIT=${METRICS_PROCESS_LIMIT:-20}
      - METRICS_GPU=${METRICS_GPU:-false}
      - INSTANCE_ID=${INSTANCE_ID}
    volumes:
      - ./data/logs:/var/log/metrics
    command: ["python", "main.py", "--interval", "${METRICS_INTERVAL:-15}", "--instance-id", "${INSTANCE_ID}", "--instance-role", "remote"]
    restart: unless-stopped

  connectivity-checker:
    build:
      context: ../connectivity-checker
    environment:
      - CONNECTIVITY_CONFIG_DIR=/etc/connectivity
      - CONNECTIVITY_INVENTORY=/etc/connectivity/node.yml
      - CONNECTIVITY_PROFILES_DIR=/etc/connectivity/profiles
      - CONNECTIVITY_TEMPLATE=/etc/connectivity/profiles/remote-default.yml
      - POLL_INTERVAL=10s
      - REQUEST_TIMEOUT=5s
      - INSTANCE_ROLE=remote
    env_file: .env
    volumes:
      - ./connectivity:/etc/connectivity:ro
      - ./data/logs:/var/log/connectivity
    command: ["python", "main.py", "--config-dir", "/etc/connectivity", "--inventory", "node.yml", "--instance-id", "${INSTANCE_ID}", "--instance-role", "remote"]
    restart: unless-stopped

