version: "3.9"

services:
  promtail:
    image: grafana/promtail:2.9.7
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file: .env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/promtail:/var/lib/promtail
    restart: unless-stopped

  connectivity-checker:
    build:
      context: ../connectivity-checker
    environment:
      - CONNECTIVITY_CONFIG_DIR=/etc/connectivity
      - CONNECTIVITY_INVENTORY=/etc/connectivity/node.yml
      - CONNECTIVITY_PROFILES_DIR=/etc/connectivity/profiles
      - CONNECTIVITY_TEMPLATE=/etc/connectivity/profiles/remote-default.yml
      - POLL_INTERVAL=10s
      - REQUEST_TIMEOUT=5s
      - INSTANCE_ROLE=remote
      - NETWORKNODE_IP=${NETWORKNODE_IP}
    env_file: .env
    volumes:
      - ./connectivity:/etc/connectivity:ro
      - ./data/logs:/var/log/connectivity
    command: ["python", "-m", "app.main", "--config-dir", "/etc/connectivity", "--inventory", "node.yml", "--instance-id", "${INSTANCE_ID}", "--instance-role", "remote"]
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.7.0
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=127.0.0.1:9100'
    env_file: .env
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    network_mode: "host"
    restart: unless-stopped

  nvidia-gpu-exporter:
    image: utkuozdemir/nvidia_gpu_exporter:1.2.0
    env_file: .env
    environment:
      - NVIDIA_GPU_EXPORTER_WEB_LISTEN_ADDRESS=127.0.0.1:9835
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  grafana-agent:
    image: grafana/agent:v0.40.0
    env_file: .env
    volumes:
      - ./grafana-agent-config.yml:/etc/agent/agent.yml:ro
    command:
      - -config.file=/etc/agent/agent.yml
      - -config.expand-env=true
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      - node-exporter
